### ISSUE TITLE
Retirer la traduction d'exemples de code

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-fr#143]
Il a été décidé de ne pas traduire les exemples de code. Mais plusieurs exemples ont été déjà traduits.

Rectifier les exemples traduits en récupérant le code de docs.
Les commentaires seuls peuvent être traduits.

**Comment by tlagoda** [comment]
On a une liste des pages ayant été traduite avant la décision de ne pas traduire le code ? Ou faut checker ?

**Comment by edimitchel** [comment]
je peux difficilement te dire, faut regarder les premières PR effectuées

**Comment by arnauddoub** [comment]
Ce genre de traduction est a rectifier ou c'est bon ?

```html
<!-- Template de MyComponent utilisant $attrs -->
<p :class="$attrs.class">Hello !</p>
<span>Ceci est un composant enfant</span>
```

**Comment by edimitchel** [comment]
Je dirai qu'il faudrait rectifier, seuls les commentaires sont à traduire

**Comment by arnauddoub** [comment]
Et vous voulez faire une branche pour toutes les rectifications ou une branche par page à rectifier ?

**Comment by tlagoda** [comment]
Honnêtement comme tu le sens! Même si perso j'essaie de faire une branche / MR par "sujet", ça permet d'y voir plus clair je trouve. 👍

**Comment by tlagoda** [comment]
@arnauddoub tu as trouvé des pages où il reste des exemples traduits ?

**Comment by arnauddoub** [comment]
Vous pensez faut également rectifier les tutoriels ?
https://github.com/vuejs-translations/docs-fr/blob/main/src/tutorial/src/step-14/description.md#slots-slots

**Comment by tlagoda** [comment]
Hmmm pour moi pas forcément! Un avis @edimitchel ?

**Comment by edimitchel** [comment]
Non, les exemples hors du guide sont exempts de cette issue.
J'ai refait une passe et rectifié ce qui restait à faire. C'est désormais réglé. Je clos.
