### ISSUE TITLE
Lien mort

### ISSUE THREAD

**Issue by kize5** [vuejs-translations/docs-fr#301]
Ce lien est hs, je fais juste remonter l'info, merci pour votre taf ! :)

Page non trouvée : 

/v2/cookbook/using-axios-to-consume-apis.html

**Comment by tlagoda** [comment]
Hello merci pour ton retour! Tu pourrais donner plus d'infos ? Où se trouve ce lien stp ? 
Merci à toi :)

**Comment by edimitchel** [comment]
Si c'est pour la version 2 de la version française, le lien qui fonctionne est: https://v2.fr.vuejs.org/v2/cookbook/using-axios-to-consume-apis.html

Donne nous quelques info @kize5 à propos de ce lien mort pour comprendre comment es-tu tombé dessus :)

**Comment by edimitchel** [comment]
Le problème est désormais réglé ;)
