### ISSUE TITLE
Mauvais lien

### ISSUE THREAD

**Issue by kiryoku-ai** [vuejs-translations/docs-fr#303]
Sur la page : https://fr.vuejs.org/tutorial/#step-15 

![image](https://user-images.githubusercontent.com/124686441/217884949-b7389b1a-250a-4db8-819d-caf4d1c4ed90.png)

Le href de Exemples pointe sur https://fr.vuejs.org/exemples/
(Remplacé par : https://fr.vuejs.org/examples/#hello-world ??)

**Comment by edimitchel** [comment]
Merci pour ton issue, c'est réglé :)
