### ISSUE TITLE
examples/form-bindings

### ISSUE THREAD

**Issue by tlagoda** [vuejs-translations/docs-fr#423]

**Comment by guillaumeduhan** [comment]
hello @tlagoda si tu veux que je switche sur l'une des issues pour t'aider c'est avec plaisir !

**Comment by tlagoda** [comment]
Hello, n'hésite pas! Merci à toi 💪💪

**Comment by tlagoda** [comment]
Je te laisse cet exemple!

**Comment by tlagoda** [comment]
Hello @guillaumeduhan, des nouvelles ? 😄

**Comment by guillaumeduhan** [comment]
Hello yes, je prends ça en main semaine pro 😉

**Comment by edimitchel** [comment]
@guillaumeduhan on te laisse jusqu'au **14 avril 22H**, on aimerait entamer sereinement la relecture de la doc.
