### ISSUE TITLE
Relecture de la traduction française

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-fr#458]
À planifier.

Relecture de synchro:

- [ ] #460

**Comment by tlagoda** [comment]
Idées en vrac : 
- 3 relectures => page validée
- groupement préalable des pages évoquant les "mêmes sujets", pour s'assurer que les termes soient traduits de la même manière
- mettre à jour le glossaire, de la manière la plus précise possible
- une fois les groupes de pages décidés, issue de suivi à créer
- trouver des volontaires 😢

**Comment by edimitchel** [comment]
Il serait intéressant d'avoir un suivi pragmatique via GIT pour savoir selon l'évolution ce qui a été relu et ce qui ne l'a pas été, lignes par lignes

**Comment by tisma95** [comment]
Hello, 

Moi j'ai déjà relu la partie "Les essentiels" et corrigé les problèmes que j'ai rencontrés. Je suis sur la partie "Composants en détails" précisément sur les props.

**Comment by luciegst** [comment]
Bonjour.  </br> Je me permets d'écrire ici car cette issue me semble correspondre. J'ai repéré une petite erreur dans la page src > guide > introduction.md

Dans la partie "Composition API", le console.log dans le onMounted.
```
onMounted(() => {
  console.log(`Le valeur initiale de count est ${this.count}.`)
})
```
</br>
devrait être :  

</br>

```
onMounted(() => {
  console.log(`Le valeur initiale de count est ${count.value}.`)
})
```

**Comment by tisma95** [comment]
Hello @luciegst,

Merci pour ta remonté @luciegst,

Une issue a été créé pour corriger https://github.com/vuejs-translations/docs-fr/issues/595

> Bonjour. Je me permets d'écrire ici car cette issue me semble correspondre. J'ai repéré une petite erreur dans la page src > guide > introduction.md
> 
> Dans la partie "Composition API", le console.log dans le onMounted.
> 
> ```
> onMounted(() => {
>   console.log(`Le valeur initiale de count est ${this.count}.`)
> })
> ```
> 
> 
> devrait être : 
> ```
> onMounted(() => {
>   console.log(`La valeur initiale de count est ${count.value}.`)
> })
> ```

Hello @luciegst,

Merci pour ta remonté @luciegst,

Une issue a été créée pour la correction https://github.com/vuejs-translations/docs-fr/issues/595

Ismaël
