### ISSUE TITLE
08/05/2023

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-fr#460]
https://github.com/vuejs-translations/docs-fr/commit/c0c5c18b99e291a7f28b9130c5006deff4296e2 à vérifier

**Comment by tlagoda** [comment]
@tisma95 si tu veux

**Comment by tisma95** [comment]
> @tisma95 si tu veux

J'ai pas trop compris le but de cette issue c'est quoi le but @tlagoda ?

**Comment by edimitchel** [comment]
En gros @tisma95 il s'agit de vérifier le commit en question qui est un merge de synchro assez importante.
