### ISSUE TITLE
guide/essentials/reactivity-fundamentals.md

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-fr#486]

**Comment by edimitchel** [comment]
@nobodyiam95

**Comment by edimitchel** [comment]
@timael95 tu peux t'en occuper?

**Comment by timael95** [comment]
Oui @edimitchel, j'ai prévu traduite cette page cette semaine.

**Comment by tisma95** [comment]
Hello @edimitchel,

Pull request pour la traduction de cette page.https://github.com/vuejs-translations/docs-fr/pull/505

Merci
