### ISSUE TITLE
Traduire le glossaire

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-fr#510]
Le glossaire semble tout nouveau. Disponible sur `src/glossary/index.md`, il faut s'organiser pour le traduire tout en sachant que c'est un long fichier.

Voici la liste des chapitres à traduire: prendre plusieurs en même temps.

Voici la marche à suivre : 

1. Ouvrir le glossaire sur la doc fr
2. Identifier 2 à 3 chapitres pas trop long
3. Rassembler les chapitres choisis dans la liste ci-dessous pour n'en former qu'une case à cocher
4. Créer l'issue et assignez la vous.

Attention à ne pas traduire les liens vers ce qui ne serait pas encore traduit. Par contre, pensez à bien vérifier que les références des chapitres qui vous traduisez dans le glossaire pour aligner votre traduction.

```[tasklist]
### Chapitres à traduire
- [ ] https://github.com/vuejs-translations/docs-fr/issues/527
- [ ] https://github.com/vuejs-translations/docs-fr/issues/539
- [ ] https://github.com/vuejs-translations/docs-fr/issues/578
- [ ] https://github.com/vuejs-translations/docs-fr/issues/582
- [ ] https://github.com/vuejs-translations/docs-fr/issues/529
- [ ] https://github.com/vuejs-translations/docs-fr/issues/542
- [ ] https://github.com/vuejs-translations/docs-fr/issues/543
- [ ] https://github.com/vuejs-translations/docs-fr/issues/521
- [ ] https://github.com/vuejs-translations/docs-fr/issues/602
- [ ] https://github.com/vuejs-translations/docs-fr/issues/599
- [ ] https://github.com/vuejs-translations/docs-fr/issues/601
- [ ] https://github.com/vuejs-translations/docs-fr/issues/607
- [ ] https://github.com/vuejs-translations/docs-fr/issues/609
- [ ] https://github.com/vuejs-translations/docs-fr/issues/613
- [ ] https://github.com/vuejs-translations/docs-fr/issues/617
- [ ] https://github.com/vuejs-translations/docs-fr/issues/628
- [ ] https://github.com/vuejs-translations/docs-fr/issues/630
- [ ] https://github.com/vuejs-translations/docs-fr/issues/611
- [ ] https://github.com/vuejs-translations/docs-fr/issues/632
- [ ] https://github.com/vuejs-translations/docs-fr/issues/634
- [ ] https://github.com/vuejs-translations/docs-fr/issues/572
- [ ] https://github.com/vuejs-translations/docs-fr/issues/640
- [ ] https://github.com/vuejs-translations/docs-fr/issues/574
- [ ] https://github.com/vuejs-translations/docs-fr/issues/669
- [ ] https://github.com/vuejs-translations/docs-fr/issues/671
- [ ] https://github.com/vuejs-translations/docs-fr/issues/636
- [ ] https://github.com/vuejs-translations/docs-fr/issues/644
- [ ] https://github.com/vuejs-translations/docs-fr/issues/637
- [ ] https://github.com/vuejs-translations/docs-fr/issues/575
- [ ] https://github.com/vuejs-translations/docs-fr/issues/642
- [ ] https://github.com/vuejs-translations/docs-fr/issues/638
- [ ] https://github.com/vuejs-translations/docs-fr/issues/673
- [ ] https://github.com/vuejs-translations/docs-fr/issues/565
- [x] https://github.com/vuejs-translations/docs-fr/issues/520
- [ ] https://github.com/vuejs-translations/docs-fr/issues/675
```

**Comment by DylanThomasFr** [comment]
Hey 👋

je ne suis pas trop habitué à contribuer sur de l'open source. Comment puis-je prendre une partie de la checklist qui n'est pas complétée ? Je crée juste une issue et je fais ma PR ?

**Comment by tisma95** [comment]
> Hey 👋
> 
> je ne suis pas trop habitué à contribuer sur de l'open source. Comment puis-je prendre une partie de la checklist qui n'est pas complétée ? Je crée juste une issue et je fais ma PR ?

Hello @DylanThomasFr,

Voici la procédure qu'on applique:
1. tu crées une issue à partir d'un élément de la checklist non assigné à une personne
2. tu t'assignes la issue
3. dans la page de la issue tu as sur le menu droit l'option create branch (tu créées la branche pour travailler sur ton sujet)
4. tu passes sur la branche que tu auras créée pour faire ta trad
5. quand tu seras ok avec ta trad tu peux la commiter
6. Venir sur la issue pour ouvrir une pull request (en vérifiant et cochant tous les points à vérifier avant ouverture de la pull request) en mettant comme vérificateur l'un de nous soit @edimitchel , @tlagoda ou @tisma95 tu peux aussi nous ajouter tous les trois
7. Et voilà 😄 

Si tu as des questions n'hésites pas.

Merci 
Ismaël
