### ISSUE TITLE
Not found link found in doc 

### ISSUE THREAD

**Issue by tisma95** [vuejs-translations/docs-fr#533]
Hello ici y'a un lien dans la doc Pour Node.js Stream API cette url pointe sur une page not found je sais pas qu'est ce qu'on fait dans ce cas de figure l'équipe anglaise est aussi concerné par ce sujet. Merci.
Link https://fr.vuejs.org/guide/scaling-up/ssr.html#rendering-an-app
![La fonction renderToString() rend une application Vue en HTML et renvole une - copie](https://github.com/vuejs-translations/docs-fr/assets/55036198/9f43eeb5-1fe0-40d5-856c-c994a7a5269e)
https://nodejs.org/api/stream

**Comment by tlagoda** [comment]
Hello, bien vu!
Dans ce cas, je pense que tu peux ouvrir l'issue directement sur le repo de la doc officielle! N'hésite pas à proposer la solution!

**Comment by tisma95** [comment]
Merci @tlagoda c'st fait https://github.com/vuejs/docs/issues/2445 je vais donc fermer cette issue on ouvrira une autre si mise à jour de la doc anglaise.
