### ISSUE TITLE
Translate rule in docs

### ISSUE THREAD

**Issue by tisma95** [vuejs-translations/docs-fr#548]
Hello,
Parfois je vois dans la doc les exemples traduits parfois non comme ici http://localhost:5173/guide/components/slots.html#named-slots
![Capture d’écran 2023-07-29 à 17 04 16](https://github.com/vuejs-translations/docs-fr/assets/55036198/57c8897c-8e77-4abc-b32f-44b2f9da1547)
![Capture d’écran 2023-07-29 à 17 04 29](https://github.com/vuejs-translations/docs-fr/assets/55036198/2a135057-d2c3-4a55-867d-ae0465914754)
![Capture d’écran 2023-07-29 à 17 04 40](https://github.com/vuejs-translations/docs-fr/assets/55036198/ef0d2871-14b0-4b25-85b1-81223b9eb8c0)

Du coup je me demande quel est la règle pour la traduction des exemples ?

Merci.

**Comment by edimitchel** [comment]
Les exemples de code dans le guide ne sont pas traduits seuls les commentaires le sont.

Dans la partie Exemples, là on se prend la liberté de tout traduire.
