### ISSUE TITLE
"count" traduit en partie seulement en "compteur"

### ISSUE THREAD

**Issue by MEmmanuel** [vuejs-translations/docs-fr#680]
Dans "Qu'est-ce que Vue?"​, le script affiche un simple compteur.
Le compteur utilise la variable `count` en anglais, traduit en `compteur`, sauf dans le `setup`

![image](https://github.com/vuejs-translations/docs-fr/assets/8722860/c73925f8-0bbf-461d-8195-dbce2a645990)

**Comment by edimitchel** [comment]
Hello @MEmmanuel, merci pour ton issue, mais en fait, on a décidé de ne plus traduire les exemples dans le guide.

Peux-tu utiliser count plutôt compteur pour n'avoir que du code en anglais si tu veux bien ?

**Comment by MEmmanuel** [comment]
Hello !
A yes, j'ai hésité à faire dans un sens ou dans l'autre.
Du coup, je change partout pour `count `
La PR est à jour :)
