### ISSUE TITLE

        chore(deps): bump @vue/theme from 2.2.4 to 2.2.5
    

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-fr#718]
New updates on head repo.
https://github.com/vuejs/docs/commit/0fe5b3ddaecc3abc0a329cfa53b9708a9674ca09

**Comment by tisma95** [comment]
çà c'est bine à jour sur notre version on pas nécessaire il me semble. Tu confirmes  @edimitchel ?

**Comment by edimitchel** [comment]
Yes!
