### ISSUE TITLE

        use 3.4 beta
    

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-fr#791]
New updates on head repo.
https://github.com/vuejs/docs/commit/7d08ac37ea66840fdda96858a2c5eb93629747f9

**Comment by tisma95** [comment]
Pour ici @edimitchel on fait quoi c'est une mise à jour de package peut être récupérer le package et package-lock du head vers la version française au lieu de le faire à la main et avoir des divergence dans le pnpm-lock.

**Comment by edimitchel** [comment]
C'est déjà fait en fait
