### ISSUE TITLE

        Fix terminology and grammar
    

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/docs-fr#792]
New updates on head repo.
https://github.com/vuejs/docs/commit/c0f3490a654f4f18a819a73645334b9bf59d3ec2

**Comment by FrankySnow** [comment]
Hello,
peut-on en profiter pour faire les 2 corrections suivantes ? Merci !
<hr>

https://github.com/vuejs-translations/docs-fr/blob/8a5ccad9818dc47900ebdd250418c56365593798/src/api/reactivity-utilities.md?plain=1#L25
s/synthétique/syntaxique
<hr>

https://github.com/vuejs-translations/docs-fr/blob/8a5ccad9818dc47900ebdd250418c56365593798/src/api/reactivity-utilities.md?plain=1#L206
s/liée/liées
